### PR TITLE
remove unused JUnit 5

### PR DESCRIPTION
**Pull request by elharo**

### CODE REVIEW

**Comment by bmarwell** [comment]
0 / -1.
While true, this is unused, I'd rather see the junit tests executed by the junit-vintage-engine as this plugin is highly dependent on more recent java versions. As this is a new plugin, the changes would be fairly easy to do and no test would need to be rewritten.

Btw: introduced by https://github.com/apache/maven-jlink-plugin/pull/9

**Comment by elharo** [comment]
I tend to fall on the side of not adding any unnecessary dependencies. The simpler we keep the tree the better.

I'm also hesitant to introduce JUnit 5 into the project when everything else and all existing code is using JUnit 4.

**Review by slachiewicz — COMMENTED** [review]
-1, let's move to Junit5 instead of 4

**Comment by khmarbaise** [comment]
-1 Move to JUnit Jupiter aka JUnit 5...

**Pull request closed without merging**
