### PR TITLE
[MJLINK-41] add support for --add-options argument (JDK14+).

### PR DESCRIPTION
**Pull request by bmarwell**
[Issue 41](https://issues.apache.org/jira/projects/MJLINK/issues/MJLINK-41) suggests three enhancements:

* Choose the main module (the one with the main class that should be startet)
  => already implemented
* Provide additional parameters (e.g. --enable-preview)
  => this PR
* Optionally, choose between java and javaw (for GUI applications)
  TBD if possible. I suggest creating a new, dedicated issue for this request.

To test the output:
Unzip the resulting artifact and grep for the args in `lib/modules`.

---

Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [X] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MJLINK) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [X] Each commit in the pull request should have a meaningful subject line and body.
 - [X] Format the pull request title like `[MJLINK-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MJLINK-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [X] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [X] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.
 - [X] You have run the integration tests successfully (`mvn -Prun-its clean verify`).

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [X] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [X] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by sormuras** [comment]
As this PR introduces a feature for Java 14+, can you please also extend the java axis with `, 15`?

https://github.com/apache/maven-jlink-plugin/blob/5e2b1272727400d81eb64a3de50557f343097319/.github/workflows/maven.yml#L28

**Review by elharo — COMMENTED** [review]
What happens if someone builds the project with JDK 8 or 11? We can't require JDK 14+ for building.

**Comment by bmarwell** [comment]
> What happens if someone builds the project with JDK 8 or 11? We can't require JDK 14+ for building.

Then the integration test is not being executed. You need at least a toolchain to execute the ITs, but that has been in this project since ever.

**Review by rmannibucau — APPROVED** [review]
Small point: should jvm version be checked to fail if it is not supported? 

But an important feature soon!

**Comment by bmarwell** [comment]
> Small point: should jvm version be checked to fail if it is not supported?

Thanks, I will add a nice error message if neither the toolchain (if present) nor the maven JDK is at least Java 14.

**Comment by bmarwell** [comment]
@rmannibucau please re-review.

Things to watch:
* Language and spelling
* Is  the MojoFailureException thrown when it shouldn’t? See this line: 
  `            if ( !toolchainPrivate.matchesRequirements( singletonMap( "jdk", "14" ) ) )    `
* Are the ITs properly defined?

**Review by rmannibucau — APPROVED** [review]

**Comment by bmarwell** [comment]
Squashed build result green: https://ci-builds.apache.org/blue/organizations/jenkins/Maven%2Fmaven-box%2Fmaven-jlink-plugin/detail/MJLINK-41/2/pipeline/

**Comment by bmarwell** [comment]
Closed with https://github.com/apache/maven-jlink-plugin/commit/7a44a7e328e73168e872bf54e06c3d92d1811dc9

**Pull request closed without merging**
