### PR TITLE
(build) Add Java8 + Toolchain tests

### PR DESCRIPTION
**Pull request by bmarwell**
This PR adds a `toolchain.xml` file to `$HOME/.m2` if the build was run using a JDK 8.
The toolchain is being initialized with a Jabba-provided OpenJ9 Java 11 JDK.

This way, we can test the plugin execution when Java 8 is being used to run maven and the JDK11 will be used as a toolchain JDK für the corresponding IT.

Up to now, we did not have a test which tested the JDK8+toolchain path.

--- 

Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MJLINK) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [X] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[MJLINK-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MJLINK-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [X] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [X] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.
 - [X] You have run the integration tests successfully (`mvn -Prun-its clean verify`).

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [X] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [X] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by sparsick** [comment]
@bmarwell I had a look on the output of the Github Action. I think the toolchain is used because of this debug line:

```shell
DEBUG] Reading user toolchains from /home/runner/work/maven-jlink-plugin/maven-jlink-plugin/it-toolchains.xml
```
But maybe it is ignored, because the path to jdkhome in toolchain is wrong? (see attachment)

grafik

**Comment by bmarwell** [comment]
Thanks @sparsick . Now it starts executing the IT, but it fails in the verify phase due to a missing target directoy. If I run this test locally (using JDK8 and a toolchain), it works flawlessly.
https://github.com/bmarwell/maven-jlink-plugin/runs/1462630220?check_suite_focus=true

**Comment by sparsick** [comment]
@bmarwell I could reproduce the build failure on my local machine (Kubuntu 20.04). I need some more time to analyse why it fails.

**Comment by bmarwell** [comment]
Thanks, looks like I need to use both `--global-toolchains` and `-t`.

**Comment by sparsick** [comment]
Maybe you can set the toolchain in invoker.properties (https://maven.apache.org/plugins/maven-invoker-plugin/run-mojo.html#invokerPropertiesFile). I see following properties:

```

# A mapping for toolchain to ensure it exists
# Since plugin version 3.2.0
invoker.toolchain.<type>.<provides> = value
invoker.toolchain.jdk.version = 11
```

**Comment by bmarwell** [comment]
Hi Sandra,

in this run I set both global and non-global toolchains:
https://github.com/bmarwell/maven-jlink-plugin/runs/1474825278?check_suite_focus=true

As you can see, the IT maven invocation will always look in the home directory.

Somehow we need to promote that file or find a way to write it to the correct location instead.

**Comment by sparsick** [comment]
@bmarwell I could fix the build on my machine when I set following property in `invoker.properties`

```properties
invoker.goals = clean install -t <path to it-toolchains.xml>
```
On the commandline I had to run `mvn verfiy -t it-toolchains.xml` otherwise Maven skipped the tests. 

Maybe it is a bug in invoker plugin that it ignores `-t ` flag?

Other thing that I notice, in the pom of MJLINK-36_toolchainjdk8 `compiler.target` and `compiler.source` is set to `1.9`. Is this correct? I have expected `1.8`.

**Comment by bmarwell** [comment]
Yes, 1.9 is correct. We do not want to use the mvn execution jdk for this test, but the toolchain jdk. 

I also think this is a bug. Install must not be necessary.

**Comment by sparsick** [comment]
LGTM

**Review by sparsick — APPROVED** [review]

**Review by rmannibucau — APPROVED** [review]

**Review by sormuras — COMMENTED** [review]
LGTM

The "jabba + openj9@11" could be replaced with a usage of [setup-java](https://github.com/actions/setup-java) action. Not?

**Comment by bmarwell** [comment]
> The "jabba + openj9@11" could be replaced with a usage of setup-java action. Not?

I would not know how. The Jabba plugin puts the installation path into an env variable which I use for the toolchain.
AFAIK, the setup-java action cannot do that and will always update $JAVA_HOME.

Reference: https://github.com/actions/setup-java/blob/61c9e3a719405cb24d9c40bd15467232f9ab55bc/action.yml#L49-L51

**Comment by bmarwell** [comment]
CI build: https://ci-builds.apache.org/blue/organizations/jenkins/Maven%2Fmaven-box%2Fmaven-jlink-plugin/detail/jdk8toolchain_win/1/pipeline
All green.

**Pull request merged**
