### PR TITLE
Allow for module exclusions

### PR DESCRIPTION
**Pull request by iovuio**
Sample project [a-javafx-label.zip](https://github.com/apache/maven-jlink-plugin/files/3024953/a-javafx-label.zip)

The plugin determines the modules automatically from the project
dependencies in pom.xml.

For the specific case of using javafx libraries (e.g. `javafx-graphics`)
the dependency is a placeholder for the actual dependency
javafx-graphics-win-<version>.jar.
The library designers have decided to not make those bogus dependency
actual modules and they are configured as automatic modules. If those get in
`jlink`'s module list, it will exit with an error.

Allow a way to exclude modules such that maven-jlink-plugin can be used
with those projects.

Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MJLINK) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[MJLINK-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MJLINK-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.
 - [ ] You have run the integration tests successfully (`mvn -Prun-its clean verify`).

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [x] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by michab66** [comment]
Note that a null-check on excludeModules is missing.

**Comment by iovuio** [comment]
@michab66 thank you for your notification. 
I have pushed the necessary change.
Please let me know what else is needed.

**Comment by rfscholte** [comment]
How did you test it? Can you turn that into an integration test under https://github.com/apache/maven-jlink-plugin/tree/master/src/it/projects ?

**Comment by iovuio** [comment]
@rfscholte ,

sorry for the late reply.
I tested it with the provided project in the original post of the PR.
I will look into creating the integration test based on the examples one the page you referenced.

I am closing this PR and will create another one if I succeed with the integration test.

**Pull request closed without merging**
