### PR TITLE
[MJLINK-23] Allow setting additional modulepaths

### PR DESCRIPTION
**Pull request by ggam**
There's a modulePaths property but it's missing the @parameter annotation.

-------------

Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [X] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MJLINK) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [X] Each commit in the pull request should have a meaningful subject line and body.
 - [X] Format the pull request title like `[MJLINK-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MJLINK-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [X] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [X] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.
 - [X] You have run the integration tests successfully (`mvn -Prun-its clean verify`).

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [X] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by ggam** [comment]
Sorry I thought the template was just for contributors to make sure we do the needed checks. I didn't think it was needed at all since all the checks need to be marked before it can be approved.

The commits are squashed now.

**Comment by khmarbaise** [comment]
First many thanks that you followed the guide lines. This makes my work easier. 
And yes the templates make it easy to follow them (for contributors as well as committers) and will create an email to the developers and furthermore it will create an entry into the appropriate [JIRA issue](https://issues.apache.org/jira/browse/MJLINK-23) which also contains the filled template with all information needed for a committer(s).

I will merge as soon as possible but currently we have some issues with our CI systems at the moment so it could take some time..

**Comment by khmarbaise** [comment]
It will take some time see here: https://builds.apache.org/job/maven-box/job/maven-jlink-plugin/job/MJLINK-23/

**Comment by khmarbaise** [comment]
I will thank you our INFRA Team cause they fixed the issue on the CI system very fast...So the results looks Ok. I have merged into master.
Many thanks for your contribution.

**Comment by ggam** [comment]
Thanks for all the explanations. Great to see all working.

**Pull request closed without merging**
