### PR TITLE
(no-issue) remove unused junit 4.

### PR DESCRIPTION
**Pull request by bmarwell**
… as `junit-vintage-engine` is already on the classpath.

--- 

Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MJLINK) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [X] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[MJLINK-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MJLINK-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [X] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [X] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.
 - [X] You have run the integration tests successfully (`mvn -Prun-its clean verify`).

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [X] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [X] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Review by slachiewicz — APPROVED** [review]

**Comment by elharo** [comment]
Strong no on this one. JUnit 4 is what the entire project uses. It's much better supported by tooling. JUnit 5 seems to be a completely new thing that has not achieved broad adoption. For example, I just noticed Eclipse doesn't support this. We should stick to JUnit 4 for now, and any choice to upgrade should be discussed across the community, not just within one PR in one repo.

**Comment by bmarwell** [comment]
> JUnit 5 seems to be a completely new thing

Exists since 2016. I wouldn’t call it bleeding edge.

> that has not achieved broad adoption

It will as soon as junit4 will run out of support. This plugin is a new project and has no legacy which needs conversion.

> I just noticed Eclipse doesn't support this.

While I cannot believe this is true, I have not tried it myself.  But there is a "we support it" article from 2017: https://www.eclipse.org/community/eclipse_newsletter/2017/october/article5.php

Anyway, this is not a good argument (just a good point): shiro’s reasteasy won't run in IntelliJ, maven’s multirelease-setup will not run in any IDE either. 

The truth must always be the command line tool.

> any choice to upgrade should be discussed across the community

This is a very valid argument. I will happily put it on the mailing list! Thanks for reminding us!

**Comment by pzygielo** [comment]
> For example, I just noticed Eclipse doesn't support this.

It seems to be very well supported: 
eclipse-junit

**Comment by khmarbaise** [comment]
> > JUnit 5 seems to be a completely new thing
> 
> Exists since 2016. I wouldn’t call it bleeding edge.

Yeah...I moved all my projects to JUnit Jupiter etc.
> 
> > that has not achieved broad adoption
> 
> It will as soon as junit4 will run out of support. This plugin is a new project and has no legacy which needs conversion.

JUnit Jupiter has much better things to offer which JUnit 4 has not... Extension point etc. etc...  https://junit.org/junit5/docs/current/user-guide/ (Strongly recommend to take a deep look into it...

> 
> > I just noticed Eclipse doesn't support this.
> 
Can you tell which Eclipse version?

**Pull request closed without merging**
